name: CI/CD for Medusa

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637423317288.dkr.ecr.us-east-1.amazonaws.com@v2

    - name: Build and push Docker image
      run: |
        IMAGE_URI=${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        docker build -t $IMAGE_URI ./medusa
        docker push $IMAGE_URI

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Apply Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"
